# Generated by Django 5.2.15 on 2026-07-01 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0004_orderitem_order_item_quantity_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='notification_user_idx'),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
