# Generated by Django 5.2.16 on 2026-07-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_pickup_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed_by_seller', 'تم التأكيد من العامل'), ('preparing', 'قيد التحضير'), ('ready_for_pickup', 'جاهز للاستلام'), ('completed', 'مكتمل'), ('canceled', 'ملغي')], default='pending', max_length=20),
        ),
    ]
