# Generated by Django 5.2.15 on 2026-07-01 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_location_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'centers',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120, unique=True)),
                ('name_en', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'governorates',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='KitchenGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kitchens/gallery/')),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kitchen_gallery',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sellers.sellerprofile',),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='kitchens/covers/'),
        ),
        migrations.AlterModelTable(
            name='sellerprofile',
            table='chefs',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='center_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chefs', to='sellers.center'),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='sellers.sellerprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'followers',
            },
        ),
        migrations.AddField(
            model_name='center',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='sellers.governorate'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='governorate_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chefs', to='sellers.governorate'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['approved', 'governorate_record', 'center_record'], name='chef_location_idx'),
        ),
        migrations.AddField(
            model_name='kitchengallery',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_gallery', to='sellers.sellerprofile'),
        ),
        migrations.AddIndex(
            model_name='follower',
            index=models.Index(fields=['chef', '-created_at'], name='followers_chef_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('customer', 'chef'), name='follower_customer_chef_uniq'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['governorate', 'is_active'], name='center_gov_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='center',
            constraint=models.UniqueConstraint(fields=('governorate', 'slug'), name='center_governorate_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='kitchengallery',
            index=models.Index(fields=['chef', 'sort_order'], name='kitchen_chef_sort_idx'),
        ),
    ]
