# Generated by Django 5.2.15 on 2026-07-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_center_governorate_kitchengallery_chef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governorate',
            name='icon',
            field=models.CharField(default='📍', max_length=16),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
