# Generated by Django 5.2.15 on 2026-07-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_complete_egypt_centers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governorate',
            options={'ordering': ['-estimated_population', 'name_ar']},
        ),
        migrations.AddField(
            model_name='governorate',
            name='estimated_population',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='governorate',
            name='population_as_of',
            field=models.DateField(blank=True, null=True),
        ),
    ]
