# Generated by Django 5.2.15 on 2026-07-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorite',
            table='favorites',
        ),
    ]
