# Generated by Django 5.2.15 on 2026-07-01 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favorite_table'),
        ('products', '0004_category_meal_alter_product_table_and_more'),
        ('sellers', '0004_governorate_icon_sellerprofile_experience_years_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='sellers.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='favorite_user_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('chef__isnull', False)), fields=('user', 'chef'), name='favorite_user_chef_uniq'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chef__isnull', True), ('product__isnull', False)), models.Q(('chef__isnull', False), ('product__isnull', True)), _connector='OR'), name='favorite_exactly_one_target'),
        ),
    ]
